### ISSUE TITLE
Global keyboard shortcut?

### ISSUE THREAD

**Issue by screendriver** [slawkacz/soundcloud-btn#2]
Would it be possible to add a global keyboard shortcut so I can pause / play regardless in which App I am at the moment?

For example I am working on new graphics in a external graphic program (not in the browser) and want to pause / play a track.

**Comment by slawkacz** [comment]
It already done. You can set them on chrome://extensions on the bottom.

**Comment by screendriver** [comment]
Ah thank you :+1: I didn't saw this feature.
